name: xx22221111-app

services:

  backend:
    build:
      context: ./backend
    image: xx22221111-img1
    container_name: xx22221111-back
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - xx22221111-network
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:3000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:3000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    image: xx22221111-img2
    container_name: xx22221111-front
    env_file:
      - ./env/frontend.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - xx22221111-network
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "7000:3000"

  database:
    image: mysql:8.0
    container_name: xx22221111-db
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
    networks:
      - xx22221111-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ustudent", "--password=student"]
      interval: 10s
      timeout: 10s
      retries: 6

networks:
  xx22221111-network:
    name: xx22221111-network

volumes:
  mysql-data: